variables:
  DOCKER_BUILDKIT: 1

stages:
  - build_image
  - deploy

build_image:
  stage: build_image
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - live

deploy:
  stage: deploy
  dependencies:
    - build_image
  image: elementarium/hashicorp:main
  script:
    - ./deploy/deploy-prod.sh
  environment:
    name: live
    url: https://gil0mendes.io
  only:
    - live
