variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ZOLA_VERSION: "v0.10.0"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
    - tar -xzf zola.tar.gz
    - ./zola build
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  variables:
    DOCKER_TLS_VERIFY: 1
    SERVICE_NAME: gil0mendes-website
  image: docker:latest
  script:
    - mkdir -p ~/.docker
    - echo "$TLSCACERT" > ~/.docker/ca.pem
    - echo "$TLSCERT" > ~/.docker/cert.pem
    - echo "$TLSKEY" > ~/.docker/key.pem
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker stack deploy --with-registry-auth --compose-file=docker-stack-compose.yml ${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${SERVICE_NAME}
  environment:
    name: live
    url: https://gil0mendes.io
  only:
    - live
