# The URL the site will be built for
base_url = "https://gil0mendes.io"

title = "gil0mendes"
description = "Gil Mendes personal website"

theme = "elementar"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
highlight_code = true
generate_rss = true
build_search_index = true
check_external_links = false

taxonomies = [
  { name = "categories", paginate_by = 5, rss = true },
  { name = "tags", paginate_by = 5, rss = true },
]

[extra]
author = "Gil Mendes"

alementar_title = "Gil Mendes"
elementar_menu = []
