# The URL the site will be built for
base_url = "https://gil0mendes.io"

title = "gil0mendes"
description = "Gil Mendes personal website"

theme = "elementar"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feed = true
build_search_index = true
check_external_links = false

insert_anchor_links = "right"

taxonomies = [
  { name = "categories", paginate_by = 5, rss = true, lang = "en" },
  { name = "tags", paginate_by = 5, rss = true, lang = "en" },
]

# Language configurations
default_language = "en"
[languages.pt]
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "categories", paginate_by = 5, rss = true },
  { name = "tags", paginate_by = 5, rss = true },
]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "nord"

[extra]
author = "Gil Mendes"

elementar_title = "Gil Mendes"
elementar_menu = [
  {url = "$BASE_URL/", name = "Home", lang="en"},
  {url = "$BASE_URL/pt", name = "Home", lang="pt"},
  {url = "$BASE_URL/blog", name = "Blog", lang="en"},
  {url = "$BASE_URL/pt/blog", name = "Blog", lang="pt"},
]
