name = "elementar"
description = "A elementar theme for gil0mendes.io"
license = "GPL-3.0"
homepage = "https://gil0mendes.io/"
min_version = "0.10.0"
demo = "https://gil0mendes.io/"
version = "0.1.0"

[extra]

[author]
name = "Gil Mendes"
homepage = "https://gil0mendes.io/"
