name: "Publish"

on:
  push:
    branches:
      - live

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/

      - name: Build the website
        run: |
          nix build -o ./_site

      - name: Generate sitemap
        run: |
          nix run . -- export > export.json
          nix run github:gil0mendes/emanote-sitemap-generator

      - name: Put all together
        run: |
          mkdir dist
          cp -Lr _site dist
          cp sitemap.xml dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
